version: "3"
name: "code-analysis"
services:
  node-dev:
    build: ./image/node-dev
    container_name: "node-dev"
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./node:/app
    init: true
    stdin_open: true
    tty: true
    command: [ tail, -f, /dev/null ]
